# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Nuget

on:
  push:
    tags:
      - '*'

jobs:
  pack:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore

    # pack
    - name: Pack Stargazer.Abp.ObjectStorage.Application.Contracts
      run: dotnet pack ./src/Stargazer.Abp.ObjectStorage.Application.Contracts -c Release -p:PackageVersion=${{ github.ref_name }}

    - name: Pack Stargazer.Abp.ObjectStorage.Application
      run: dotnet pack ./src/Stargazer.Abp.ObjectStorage.Application -c Release -p:PackageVersion=${{ github.ref_name }}

    - name: Pack Stargazer.Abp.ObjectStorage.HttpApi
      run: dotnet pack ./src/Stargazer.Abp.ObjectStorage.HttpApi -c Release -p:PackageVersion=${{ github.ref_name }}

    - name: Pack Stargazer.Abp.ObjectStorage.HttpApi.Client
      run: dotnet pack ./src/Stargazer.Abp.ObjectStorage.HttpApi.Client -c Release -p:PackageVersion=${{ github.ref_name }}
      
    # push to github
    - name: Push Stargazer.Abp.ObjectStorage.Application.Contracts to github
      run: dotnet nuget push ./src/Stargazer.Abp.ObjectStorage.Application.Contracts/bin/Release/Stargazer.Abp.ObjectStorage.Application.Contracts.*.nupkg --api-key ${{ secrets.GIT_PAT }} --source "https://nuget.pkg.github.com/huangmingji/index.json"

    - name: Push Stargazer.Abp.ObjectStorage.Application to github
      run: dotnet nuget push ./src/Stargazer.Abp.ObjectStorage.Application/bin/Release/Stargazer.Abp.ObjectStorage.Application.*.nupkg --api-key ${{ secrets.GIT_PAT }} --source "https://nuget.pkg.github.com/huangmingji/index.json"

    - name: Push Stargazer.Abp.ObjectStorage.HttpApi to github
      run: dotnet nuget push ./src/Stargazer.Abp.ObjectStorage.HttpApi/bin/Release/Stargazer.Abp.ObjectStorage.HttpApi.*.nupkg --api-key ${{ secrets.GIT_PAT }} --source "https://nuget.pkg.github.com/huangmingji/index.json"

    - name: Push Stargazer.Abp.ObjectStorage.HttpApi.Client to github
      run: dotnet nuget push ./src/Stargazer.Abp.ObjectStorage.HttpApi.Client/bin/Release/Stargazer.Abp.ObjectStorage.HttpApi.Client.*.nupkg --api-key ${{ secrets.GIT_PAT }} --source "https://nuget.pkg.github.com/huangmingji/index.json"


    # push to nuget
    - name: Push Stargazer.Abp.ObjectStorage.Application.Contracts to nuget
      run: dotnet nuget push ./src/Stargazer.Abp.ObjectStorage.Application.Contracts/bin/Release/Stargazer.Abp.ObjectStorage.Application.Contracts.*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate -s https://api.nuget.org/v3/index.json

    - name: Push Stargazer.Abp.ObjectStorage.Application to nuget
      run: dotnet nuget push ./src/Stargazer.Abp.ObjectStorage.Application/bin/Release/Stargazer.Abp.ObjectStorage.Application.*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate -s https://api.nuget.org/v3/index.json

    - name: Push Stargazer.Abp.ObjectStorage.HttpApi to nuget
      run: dotnet nuget push ./src/Stargazer.Abp.ObjectStorage.HttpApi/bin/Release/Stargazer.Abp.ObjectStorage.HttpApi.*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate -s https://api.nuget.org/v3/index.json

    - name: Push Stargazer.Abp.ObjectStorage.HttpApi.Client to nuget
      run: dotnet nuget push ./src/Stargazer.Abp.ObjectStorage.HttpApi.Client/bin/Release/Stargazer.Abp.ObjectStorage.HttpApi.Client.*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate -s https://api.nuget.org/v3/index.json